# Damn Vulnerable NodeJS Application

version: "2.1"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 9090:9090
    volumes:
      - .:/app
    depends_on:
      - mysql-db
    env_file:
      - ./vars.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql-db:
    image: mysql:5.7
    expose:
      - "3306"
    env_file:
      - ./vars.env
